remote_theme: chomookun/jekyll-plain
plugins:
  - jekyll-remote-theme

# theme configuration
brand-icon: /docs/assets/image/duice-icon.svg
brand-title: <img src="/docs/assets/image/duice-title.svg"/>
