# architect theme
#remote_theme: pages-themes/architect@v0.2.0
#plugins:
#  - jekyll-remote-theme

# minima theme
remote_theme: pages-themes/minima@v2.5.0
minima:
  skin: dark
plugins:
  - jekyll-remote-theme
